"""
Xcode Life Warfarin Dosing Calculator logic.

Scientific scope
----------------
- Adults only (V1 input validation: 18-120 years)
- Stable maintenance-dose estimation
- Target INR 2.0-3.0
- IWPC clinical-only or IWPC pharmacogenetic equation
- CPIC 2017 genotype/ancestry considerations layered transparently on top

Important design rules
----------------------
1. Never convert an unavailable genetic marker into a reference call.
2. Uploaded Xcode Warfarin_Input CSVs are evaluated marker-by-marker.
3. Manual PGx values must be explicit reported results; *1 must not mean "not tested".
4. For the Black/African ancestry pathway, CYP2C9 *5/*6/*8/*11 coverage must be known
   before the PGx equation is used; otherwise use the clinical IWPC equation.
5. CPIC percentage modifiers are displayed separately from the IWPC base estimate.
   V1 does not silently stack multiple modifiers into one falsely precise final dose.
6. The IWPC algorithm predicts a point estimate in mg/week (and average daily equivalent in mg/day).
   No arbitrary percentage-based "safe range" (e.g. ±20%) is generated.
"""

from __future__ import annotations

import csv
import io
import math
from dataclasses import dataclass, field
from typing import Any, Dict, Optional

EXPECTED_FILE_TYPE = "XCODE_WARFARIN_PGX_INPUT"
SCHEMA_VERSION = "1.1"

MARKERS = {
    "rs1799853": {"gene": "CYP2C9", "label": "CYP2C9 *2", "defining_alt": "T"},
    "rs1057910": {"gene": "CYP2C9", "label": "CYP2C9 *3", "defining_alt": "C"},
    "rs28371686": {"gene": "CYP2C9", "label": "CYP2C9 *5", "defining_alt": "G"},
    "rs9332131": {"gene": "CYP2C9", "label": "CYP2C9 *6", "defining_alt": "G"},
    "rs7900194": {"gene": "CYP2C9", "label": "CYP2C9 *8", "defining_alt": "A"},
    "rs28371685": {"gene": "CYP2C9", "label": "CYP2C9 *11", "defining_alt": "T"},
    "rs9923231": {"gene": "VKORC1", "label": "VKORC1 c.-1639G>A", "defining_alt": "T"},
    "rs2108622": {"gene": "CYP4F2", "label": "CYP4F2 *3", "defining_alt": "T"},
    "rs12777823": {"gene": "CYP2C cluster", "label": "rs12777823", "defining_alt": "A"},
}

CORE = ("rs1799853", "rs1057910", "rs9923231")
EXPANDED_CYP2C9 = ("rs28371686", "rs9332131", "rs7900194", "rs28371685")
ALLOWED_CYP2C9_ALLELES = {"*1", "*2", "*3", "*5", "*6", "*8", "*11"}

PGX_POPULATION_COEFF = {
    "white_other": 0.0,
    "asian": -0.1092,
    "black_african_american": -0.2760,
    "mixed_unknown": -0.1032,
}

PGX_CYP2C9_COEFF = {
    "*1/*1": 0.0,
    "*1/*2": -0.5211,
    "*1/*3": -0.9357,
    "*2/*2": -1.0616,
    "*2/*3": -1.9206,
    "*3/*3": -2.3312,
}

PGX_VKORC1_COEFF = {
    "G/G": 0.0,
    "G/A": -0.8677,
    "A/G": -0.8677,
    "A/A": -1.6974,
}

CLINICAL_POPULATION_COEFF = {
    "white_other": 0.0,
    "asian": -0.6752,
    "black_african_american": 0.4060,
    "mixed_unknown": 0.0443,
}

# Expected maintenance-dose ranges (mg/day) by CYP2C9 and VKORC1 genotype
# from U.S. FDA Coumadin prescribing information table.
FDA_LABEL_RANGES = {
    ("G/G", "*1/*1"): "5–7 mg/day",
    ("G/G", "*1/*2"): "5–7 mg/day",
    ("G/G", "*1/*3"): "3–4 mg/day",
    ("G/G", "*2/*2"): "3–4 mg/day",
    ("G/G", "*2/*3"): "3–4 mg/day",
    ("G/G", "*3/*3"): "0.5–2 mg/day",
    ("G/A", "*1/*1"): "5–7 mg/day",
    ("G/A", "*1/*2"): "3–4 mg/day",
    ("G/A", "*1/*3"): "3–4 mg/day",
    ("G/A", "*2/*2"): "3–4 mg/day",
    ("G/A", "*2/*3"): "0.5–2 mg/day",
    ("G/A", "*3/*3"): "0.5–2 mg/day",
    ("A/G", "*1/*1"): "5–7 mg/day",
    ("A/G", "*1/*2"): "3–4 mg/day",
    ("A/G", "*1/*3"): "3–4 mg/day",
    ("A/G", "*2/*2"): "3–4 mg/day",
    ("A/G", "*2/*3"): "0.5–2 mg/day",
    ("A/G", "*3/*3"): "0.5–2 mg/day",
    ("A/A", "*1/*1"): "3–4 mg/day",
    ("A/A", "*1/*2"): "3–4 mg/day",
    ("A/A", "*1/*3"): "0.5–2 mg/day",
    ("A/A", "*2/*2"): "0.5–2 mg/day",
    ("A/A", "*2/*3"): "0.5–2 mg/day",
    ("A/A", "*3/*3"): "0.5–2 mg/day",
}


class WarfarinCalculatorError(ValueError):
    pass


@dataclass
class GeneticInput:
    source: str
    meta: Dict[str, str] = field(default_factory=dict)
    markers: Dict[str, Dict[str, str]] = field(default_factory=dict)
    manual: Dict[str, Any] = field(default_factory=dict)


def _called(row: Optional[Dict[str, str]]) -> bool:
    return bool(row) and str(row.get("status", "")).strip().upper() == "CALLED"


def _all_called(markers: Dict[str, Dict[str, str]], rsids) -> bool:
    return all(_called(markers.get(rsid)) for rsid in rsids)


def parse_genetic_csv(file_bytes: bytes) -> GeneticInput:
    """Parse a Warfarin_Input CSV generated by Xcode Life Step 2B."""
    try:
        text = file_bytes.decode("utf-8-sig")
    except UnicodeDecodeError as exc:
        raise WarfarinCalculatorError("The PGx input file is not valid UTF-8 CSV.") from exc

    rows = list(csv.DictReader(io.StringIO(text)))
    if not rows:
        raise WarfarinCalculatorError("The PGx input CSV is empty.")

    if str(rows[0].get("file_type", "")).strip() != EXPECTED_FILE_TYPE:
        raise WarfarinCalculatorError("This is not a recognized Xcode Life Warfarin input file.")

    markers: Dict[str, Dict[str, str]] = {}
    for row in rows:
        rsid = str(row.get("marker", "")).strip().lower()
        if rsid:
            markers[rsid] = row

    missing_rows = [rsid for rsid in MARKERS if rsid not in markers]
    if missing_rows:
        raise WarfarinCalculatorError(
            "The Xcode Warfarin input file is malformed; expected marker rows are missing: "
            + ", ".join(missing_rows)
        )

    return GeneticInput(source="xcode_csv", meta=dict(rows[0]), markers=markers)


def parse_manual_genetic(
    *,
    cyp2c9_allele1: str = "",
    cyp2c9_allele2: str = "",
    expanded_tested: bool = False,
    vkorc1: str = "",
    cyp4f2: str = "",
    rs12777823: str = "",
) -> Optional[GeneticInput]:
    """Create a safe manual PGx object from explicitly reported values."""
    values = [cyp2c9_allele1, cyp2c9_allele2, vkorc1, cyp4f2, rs12777823]
    if not any(str(v).strip() for v in values) and not expanded_tested:
        return None

    a1 = str(cyp2c9_allele1).strip()
    a2 = str(cyp2c9_allele2).strip()
    if bool(a1) != bool(a2):
        raise WarfarinCalculatorError("Enter both CYP2C9 alleles, or leave both as Not available.")
    if a1 and (a1 not in ALLOWED_CYP2C9_ALLELES or a2 not in ALLOWED_CYP2C9_ALLELES):
        raise WarfarinCalculatorError("The manual CYP2C9 result contains an unsupported allele for this calculator.")

    vkorc1 = str(vkorc1).strip().upper().replace(" ", "")
    if vkorc1 and vkorc1 not in PGX_VKORC1_COEFF:
        raise WarfarinCalculatorError("VKORC1 must be G/G, G/A, or A/A in clinical -1639 notation.")

    cyp4f2 = str(cyp4f2).strip()
    if cyp4f2 and cyp4f2 not in {"*1/*1", "*1/*3", "*3/*1", "*3/*3"}:
        raise WarfarinCalculatorError("CYP4F2 must be *1/*1, *1/*3, or *3/*3 when entered manually.")

    rs12777823 = str(rs12777823).strip().upper().replace(" ", "")
    if rs12777823 and rs12777823 not in {"G/G", "G/A", "A/G", "A/A"}:
        raise WarfarinCalculatorError("rs12777823 must be G/G, G/A, or A/A when entered manually.")

    return GeneticInput(
        source="manual",
        manual={
            "cyp2c9_allele1": a1,
            "cyp2c9_allele2": a2,
            "expanded_tested": bool(expanded_tested),
            "vkorc1": vkorc1,
            "cyp4f2": cyp4f2.replace("*3/*1", "*1/*3"),
            "rs12777823": rs12777823.replace("A/G", "G/A"),
        },
    )


def _defining_allele_count(markers: Dict[str, Dict[str, str]], rsid: str) -> Optional[int]:
    """Count the defining allele from VCF GT + ALT, including multiallelic rows."""
    row = markers.get(rsid)
    if not _called(row):
        return None

    alt_field = str(row.get("alt", "")).strip()
    alt_alleles = [x.strip() for x in alt_field.split(",") if x.strip() and x.strip() != "."]
    defining_alt = MARKERS[rsid]["defining_alt"]

    if defining_alt not in alt_alleles:
        return 0

    defining_vcf_index = alt_alleles.index(defining_alt) + 1
    gt = str(row.get("vcf_gt", "")).replace("|", "/").split("/")
    if len(gt) != 2 or any(not x.isdigit() for x in gt):
        return None
    return sum(int(x) == defining_vcf_index for x in gt)


def _manual_diplotype(genetic: GeneticInput) -> str:
    a1 = genetic.manual.get("cyp2c9_allele1", "")
    a2 = genetic.manual.get("cyp2c9_allele2", "")
    return f"{a1}/{a2}" if a1 and a2 else ""


def _iwpc_cyp2c9_category(genetic: GeneticInput) -> Optional[str]:
    """Map only CYP2C9 *2/*3 copy counts into the historical IWPC base category."""
    if genetic.source == "manual":
        a1 = genetic.manual.get("cyp2c9_allele1", "")
        a2 = genetic.manual.get("cyp2c9_allele2", "")
        if not a1 or not a2:
            return None
        n2 = int(a1 == "*2") + int(a2 == "*2")
        n3 = int(a1 == "*3") + int(a2 == "*3")
    else:
        if not _all_called(genetic.markers, ("rs1799853", "rs1057910")):
            return None
        n2 = _defining_allele_count(genetic.markers, "rs1799853")
        n3 = _defining_allele_count(genetic.markers, "rs1057910")
        if n2 is None or n3 is None:
            return None

    mapping = {
        (0, 0): "*1/*1",
        (1, 0): "*1/*2",
        (2, 0): "*2/*2",
        (0, 1): "*1/*3",
        (0, 2): "*3/*3",
        (1, 1): "*2/*3",
    }
    return mapping.get((n2, n3))


def _vkorc1_category(genetic: GeneticInput) -> Optional[str]:
    if genetic.source == "manual":
        value = str(genetic.manual.get("vkorc1", "")).upper().replace(" ", "")
        return value if value in PGX_VKORC1_COEFF else None

    if not _called(genetic.markers.get("rs9923231")):
        return None

    stored = str(genetic.meta.get("vkorc1_clinical_1639", "")).upper().replace(" ", "")
    if stored in PGX_VKORC1_COEFF:
        return stored

    # GRCh38 genomic representation is C>T; conventional clinical notation is -1639G>A.
    genotype = str(genetic.markers["rs9923231"].get("genotype", "")).replace("|", "/")
    alleles = genotype.split("/")
    if len(alleles) != 2:
        return None
    complement = {"C": "G", "T": "A", "G": "C", "A": "T"}
    try:
        converted = [complement[a] for a in alleles]
    except KeyError:
        return None
    if set(converted) == {"G", "A"}:
        return "G/A"
    out = "/".join(converted)
    return out if out in PGX_VKORC1_COEFF else None


def _expanded_complete(genetic: GeneticInput) -> bool:
    if genetic.source == "manual":
        return bool(genetic.manual.get("expanded_tested"))
    return _all_called(genetic.markers, EXPANDED_CYP2C9)


def _expanded_counts(genetic: GeneticInput) -> list[int]:
    if genetic.source == "manual":
        a1 = genetic.manual.get("cyp2c9_allele1", "")
        a2 = genetic.manual.get("cyp2c9_allele2", "")
        stars = ("*5", "*6", "*8", "*11")
        return [int(a1 == s) + int(a2 == s) for s in stars]
    out = []
    for rsid in EXPANDED_CYP2C9:
        count = _defining_allele_count(genetic.markers, rsid)
        out.append(count or 0)
    return out


def _cyp4f2_copies(genetic: GeneticInput) -> Optional[int]:
    if genetic.source == "manual":
        d = genetic.manual.get("cyp4f2", "")
        if not d:
            return None
        return d.count("*3")
    return _defining_allele_count(genetic.markers, "rs2108622")


def _rs127_copies(genetic: GeneticInput) -> Optional[int]:
    if genetic.source == "manual":
        gt = genetic.manual.get("rs12777823", "")
        if not gt:
            return None
        return gt.split("/").count("A")
    return _defining_allele_count(genetic.markers, "rs12777823")


def _actual_cyp2c9_diplotype(genetic: GeneticInput) -> str:
    if genetic.source == "manual":
        return _manual_diplotype(genetic)
    return str(genetic.meta.get("cyp2c9_diplotype", "")).strip()


def _cyp4f2_display(genetic: GeneticInput) -> str:
    if genetic.source == "manual":
        return str(genetic.manual.get("cyp4f2", "")).strip()
    d = str(genetic.meta.get("cyp4f2_diplotype", "")).strip()
    if d:
        return d
    count = _cyp4f2_copies(genetic)
    if count is None:
        return "Unavailable"
    return {0: "*1/*1", 1: "*1/*3", 2: "*3/*3"}.get(count, "Available")


def _validate_clinical_inputs(age: int, height_cm: float, weight_kg: float, population: str) -> None:
    if not 18 <= age <= 120:
        raise WarfarinCalculatorError("Age must be between 18 and 120 years.")
    if not 100 <= height_cm <= 250:
        raise WarfarinCalculatorError("Height must be entered in centimeters (100-250 cm).")
    if not 25 <= weight_kg <= 350:
        raise WarfarinCalculatorError("Weight must be entered in kilograms (25-350 kg).")
    if population not in PGX_POPULATION_COEFF:
        raise WarfarinCalculatorError("Select a valid IWPC population category.")


def _age_decades(age: int) -> int:
    return min(math.floor(age / 10), 9)


def clinical_iwpc_weekly_dose(*, age: int, height_cm: float, weight_kg: float,
                              population: str, amiodarone: bool, enzyme_inducer: bool) -> float:
    value = (
        4.0376
        - 0.2546 * _age_decades(age)
        + 0.0118 * height_cm
        + 0.0134 * weight_kg
        + CLINICAL_POPULATION_COEFF[population]
        + (1.2799 if enzyme_inducer else 0.0)
        - (0.5695 if amiodarone else 0.0)
    )
    if value <= 0:
        raise WarfarinCalculatorError("The clinical IWPC equation returned an invalid dose.")
    return value ** 2


def pgx_iwpc_weekly_dose(*, age: int, height_cm: float, weight_kg: float,
                         population: str, amiodarone: bool, enzyme_inducer: bool,
                         cyp2c9: str, vkorc1: str) -> float:
    value = (
        5.6044
        - 0.2614 * _age_decades(age)
        + 0.0087 * height_cm
        + 0.0128 * weight_kg
        + PGX_VKORC1_COEFF[vkorc1]
        + PGX_CYP2C9_COEFF[cyp2c9]
        + PGX_POPULATION_COEFF[population]
        + (1.1816 if enzyme_inducer else 0.0)
        - (0.5503 if amiodarone else 0.0)
    )
    if value <= 0:
        raise WarfarinCalculatorError("The pharmacogenetic IWPC equation returned an invalid dose.")
    return value ** 2


def _pgx_notes(genetic: GeneticInput, population: str, african_context: str,
               weekly_dose: float) -> list[dict]:
    notes: list[dict] = []

    detected_expanded = sum(_expanded_counts(genetic))
    if detected_expanded == 1:
        strength = "Moderate" if population == "black_african_american" else "Optional"
        notes.append({
            "title": "Additional CYP2C9 reduced/no-function allele detected (*5, *6, *8, or *11)",
            "strength": strength,
            "text": "CPIC recommends/considers decreasing the calculated dose by 15–30% for one CYP2C9 *5, *6, *8, or *11 allele. (Separate guideline consideration; not automatically combined into the IWPC estimate).",
            "range": [round(weekly_dose * 0.70, 1), round(weekly_dose * 0.85, 1)],
        })
    elif detected_expanded >= 2:
        strength = "Moderate" if population == "black_african_american" else "Optional"
        notes.append({
            "title": "Two additional CYP2C9 variant alleles detected (*5, *6, *8, or *11)",
            "strength": strength,
            "text": "CPIC notes that a larger reduction, approximately 20–40%, may be needed when two relevant variant alleles are present. (Separate guideline consideration; not automatically combined into the IWPC estimate).",
            "range": [round(weekly_dose * 0.60, 1), round(weekly_dose * 0.80, 1)],
        })

    # CYP4F2 rs2108622 (CYP4F2*3): CPIC optional 5-10% increase in non-African ancestry only.
    cyp4f2 = _cyp4f2_copies(genetic)
    if population != "black_african_american" and cyp4f2 and cyp4f2 > 0:
        notes.append({
            "title": "CYP4F2*3 (rs2108622 T carrier) detected",
            "strength": "Optional",
            "text": "CPIC considers an optional 5–10% increase in the calculated dose for non-African ancestry. (Separate guideline consideration; not automatically combined into the IWPC estimate).",
            "range": [round(weekly_dose * 1.05, 1), round(weekly_dose * 1.10, 1)],
        })

    # rs12777823: CPIC recommendation is specific to African Americans (10-25% decrease for A/G or A/A).
    rs127 = _rs127_copies(genetic)
    if population == "black_african_american" and rs127 and rs127 > 0:
        if african_context == "african_american":
            notes.append({
                "title": "rs12777823 A allele detected in African American patient",
                "strength": "Moderate",
                "text": "CPIC recommends a 10–25% dose decrease for African Americans with rs12777823 A/G or A/A. The evidence cited by CPIC derives primarily from individuals of substantial West African ancestry. (Separate guideline consideration; not automatically combined into the IWPC estimate).",
                "range": [round(weekly_dose * 0.75, 1), round(weekly_dose * 0.90, 1)],
            })
        else:
            notes.append({
                "title": "rs12777823 A allele detected — no dose adjustment applied",
                "strength": "Informational only",
                "text": (
                    "CPIC recommends a 10–25% dose reduction for African American patients with rs12777823 A/G or A/A. "
                    "Evidence supporting this recommendation comes primarily from African Americans, and its applicability "
                    "to other African populations is uncertain.\n\n"
                    "Because the relevant African American population context was not confirmed, this calculator does not "
                    "apply the rs12777823 dose adjustment."
                ),
                "range": None,
            })

    return notes


def _genetic_summary(genetic: GeneticInput, cyp2c9_base: Optional[str], vkorc1: Optional[str]) -> Dict[str, Any]:
    actual = _actual_cyp2c9_diplotype(genetic)

    if not cyp2c9_base:
        iwpc_cyp2c9_text = "Unavailable"
    elif actual in {"*1/*1", "*1/*2", "*1/*3", "*2/*2", "*2/*3", "*3/*3"}:
        if actual == "*1/*1":
            iwpc_cyp2c9_text = "*1/*1 (reference)"
        else:
            iwpc_cyp2c9_text = cyp2c9_base
    else:
        if cyp2c9_base == "*1/*1":
            iwpc_cyp2c9_text = "No *2 or *3 coefficient applied"
        else:
            iwpc_cyp2c9_text = f"{cyp2c9_base} coefficient applied"

    additional_cyp2c9_finding = ""
    stars_detected = []
    if genetic.source == "manual":
        a1 = genetic.manual.get("cyp2c9_allele1", "")
        a2 = genetic.manual.get("cyp2c9_allele2", "")
        for s in ("*5", "*6", "*8", "*11"):
            if a1 == s or a2 == s:
                stars_detected.append(s)
    else:
        for rsid in EXPANDED_CYP2C9:
            c = _defining_allele_count(genetic.markers, rsid)
            if c and c > 0:
                stars_detected.append(MARKERS[rsid]["label"].replace("CYP2C9 ", ""))
    if stars_detected:
        additional_cyp2c9_finding = f"CYP2C9 {', '.join(stars_detected)} detected"

    return {
        "source": genetic.source,
        "sample_id": genetic.meta.get("sample_id", ""),
        "pharmcat_version": genetic.meta.get("pharmcat_version", ""),
        "source_type": genetic.meta.get("source_type", ""),
        "cyp2c9_reported": actual or "Unavailable",
        "cyp2c9_diplotype": actual or "Unavailable",
        "cyp2c9_phenotype": genetic.meta.get("cyp2c9_phenotype", ""),
        "iwpc_cyp2c9_base": cyp2c9_base or "Unavailable",
        "iwpc_cyp2c9_input_text": iwpc_cyp2c9_text,
        "additional_cyp2c9_finding": additional_cyp2c9_finding,
        "vkorc1": vkorc1 or "Unavailable",
        "cyp4f2_diplotype": _cyp4f2_display(genetic),
        "rs12777823": genetic.manual.get("rs12777823", "") if genetic.source == "manual" else genetic.meta.get("rs12777823", ""),
        "expanded_cyp2c9_coverage_complete": _expanded_complete(genetic),
    }


def get_fda_label_range(actual_cyp2c9: Optional[str], vkorc1: Optional[str]) -> Optional[str]:
    """Look up expected maintenance-dose range from FDA Coumadin label by actual CYP2C9 and VKORC1.

    Only applies when the patient's actual reported diplotype strictly matches one of the 6
    diplotypes present in the FDA table (*1/*1, *1/*2, *1/*3, *2/*2, *2/*3, *3/*3).
    Does NOT map expanded alleles (e.g. *1/*11, *1/*5) to *1/*1.
    """
    if not actual_cyp2c9 or not vkorc1:
        return None
    valid_cyp2c9 = {"*1/*1", "*1/*2", "*1/*3", "*2/*2", "*2/*3", "*3/*3"}
    if actual_cyp2c9 not in valid_cyp2c9:
        return None
    return FDA_LABEL_RANGES.get((vkorc1, actual_cyp2c9))


def calculate(*, age: int, height_cm: float, weight_kg: float, population: str,
              amiodarone: bool, enzyme_inducer: bool,
              genetic: Optional[GeneticInput] = None,
              african_context: str = "unknown") -> Dict[str, Any]:
    """Calculate the most appropriate V1 estimate and return transparent metadata."""
    _validate_clinical_inputs(age, height_cm, weight_kg, population)

    if african_context not in {"unknown", "african_american", "other_african"}:
        raise WarfarinCalculatorError("Invalid African-ancestry context value.")

    method = "clinical_iwpc"
    method_label = "IWPC clinical algorithm"
    pathway_reason = ""
    fallback_reason = ""
    notes: list[dict] = []
    warnings: list[str] = []
    genetic_summary: Dict[str, Any] = {}

    can_use_pgx = False
    cyp2c9 = None
    vkorc1 = None

    if genetic is not None:
        cyp2c9 = _iwpc_cyp2c9_category(genetic)
        vkorc1 = _vkorc1_category(genetic)
        core_complete = bool(cyp2c9 and vkorc1)
        expanded_complete = _expanded_complete(genetic)

        if core_complete:
            if population == "black_african_american" and not expanded_complete:
                fallback_reason = (
                    "For this population pathway, CYP2C9 *5, *6, *8 and *11 were not all available. "
                    "In line with CPIC guidance, this estimate uses the IWPC clinical dosing algorithm "
                    "without genotype information. No missing genotype was assumed to be normal."
                )
                pathway_reason = fallback_reason
            else:
                can_use_pgx = True
                pathway_reason = "CYP2C9 and VKORC1 information required for the pharmacogenetic pathway was available."
        else:
            fallback_reason = (
                "Complete PGx information required for the pharmacogenetic pathway was not available. "
                "No missing genotype was assumed to be normal."
            )
            pathway_reason = fallback_reason

        genetic_summary = _genetic_summary(genetic, cyp2c9, vkorc1)

    if can_use_pgx:
        method = "pharmacogenetic_iwpc"
        method_label = "IWPC pharmacogenetic algorithm"
        weekly = pgx_iwpc_weekly_dose(
            age=age,
            height_cm=height_cm,
            weight_kg=weight_kg,
            population=population,
            amiodarone=amiodarone,
            enzyme_inducer=enzyme_inducer,
            cyp2c9=cyp2c9,
            vkorc1=vkorc1,
        )
        weekly_mg = round(weekly, 1)
        notes = _pgx_notes(genetic, population, african_context, weekly_mg)
    else:
        weekly = clinical_iwpc_weekly_dose(
            age=age,
            height_cm=height_cm,
            weight_kg=weight_kg,
            population=population,
            amiodarone=amiodarone,
            enzyme_inducer=enzyme_inducer,
        )
        weekly_mg = round(weekly, 1)
        if genetic is None:
            fallback_reason = (
                "Complete PGx information required for the pharmacogenetic pathway was not available. "
                "No missing genotype was assumed to be normal."
            )
            pathway_reason = fallback_reason

    if age < 20:
        warnings.append("Very few patients younger than 20 years contributed to the original IWPC model; interpret with caution.")
    if age > 90:
        warnings.append("Very few patients older than 90 years contributed to the original IWPC model; interpret with caution.")

    if genetic is not None and genetic.source == "xcode_csv" and str(genetic.meta.get("source_type", "")).lower() == "consumer_raw_dna":
        warnings.append(
            "PGx data note: Genetic results derived from consumer raw DNA files may have incomplete marker coverage and are not equivalent to comprehensive clinical pharmacogenetic testing. Xcode Life does not perform clinical diagnostic genotyping; actionable findings require confirmation with an appropriately validated clinical PGx test before altering therapy."
        )

    if genetic is not None and can_use_pgx:
        phenotype = str(genetic.meta.get("cyp2c9_phenotype", "")).lower()
        actual = _actual_cyp2c9_diplotype(genetic)
        is_poor_metabolizer = (
            "poor metabolizer" in phenotype
            or cyp2c9 in {"*2/*3", "*3/*3"}
            or actual in {"*2/*3", "*3/*3", "*3/*5", "*3/*6", "*3/*8", "*3/*11"}
        )
        if is_poor_metabolizer:
            warnings.append(
                "This genotype is associated with markedly reduced CYP2C9 activity. CPIC advises considering an alternative oral anticoagulant in patients with CYP2C9 poor-metabolizer genotypes, particularly when accompanied by increased VKORC1 sensitivity. Treatment selection remains a clinician decision. Confirm the relevant genotype using an appropriate clinical PGx test before altering therapy."
            )

    weekly_mg = round(weekly, 1)
    daily_average_mg = round(weekly / 7.0, 1)

    dose_summary = (
        f"Estimated stable maintenance dose: {weekly_mg:.1f} mg/week\n"
        f"Average daily equivalent: {daily_average_mg:.1f} mg/day"
    )

    actual_cyp2c9 = _actual_cyp2c9_diplotype(genetic) if genetic else ""
    fda_range = get_fda_label_range(actual_cyp2c9, vkorc1)
    fda_reference = None
    if fda_range:
        fda_reference = (
            f"Expected maintenance-dose range in U.S. FDA Coumadin labeling for "
            f"CYP2C9 {actual_cyp2c9} and VKORC1 {vkorc1}: {fda_range}."
        )

    return {
        "method": method,
        "method_label": method_label,
        "pathway_reason": pathway_reason,
        "weekly_mg": weekly_mg,
        "daily_average_mg": daily_average_mg,
        "dose_summary": dose_summary,
        "target_inr": "2.0-3.0",
        "fallback_message": fallback_reason,
        "genetic_summary": genetic_summary,
        "pgx_notes": notes,
        "warnings": warnings,
        "fda_label_range": fda_range,
        "fda_label_reference": fda_reference,
        "calculator_version": "1.3.1",
    }


def self_test() -> None:
    weekly = pgx_iwpc_weekly_dose(
        age=70,
        height_cm=180,
        weight_kg=75,
        population="white_other",
        amiodarone=False,
        enzyme_inducer=False,
        cyp2c9="*1/*1",
        vkorc1="G/A",
    )
    expected = 29.51640241
    assert abs(weekly - expected) < 1e-8, (weekly, expected)

    clinical = clinical_iwpc_weekly_dose(
        age=70,
        height_cm=180,
        weight_kg=75,
        population="white_other",
        amiodarone=False,
        enzyme_inducer=False,
    )
    assert clinical > 0

    manual = parse_manual_genetic(
        cyp2c9_allele1="*1",
        cyp2c9_allele2="*11",
        expanded_tested=True,
        vkorc1="G/G",
        cyp4f2="*1/*1",
        rs12777823="G/A",
    )
    result = calculate(
        age=64,
        height_cm=172,
        weight_kg=78,
        population="white_other",
        amiodarone=False,
        enzyme_inducer=False,
        genetic=manual,
    )
    assert result["method"] == "pharmacogenetic_iwpc"
    assert result["genetic_summary"]["iwpc_cyp2c9_base"] == "*1/*1"
    assert result["fda_label_range"] is None
    assert any("CYP2C9" in note["title"] for note in result["pgx_notes"])
